### PR TITLE
nEXT is the only maintained web browser

### PR DESCRIPTION
**Pull request by vindarel**
Hello,

I don't like this list to not being a minimum curated and listing altogether unmaintained and current software. So I wonder if you would accept this solution: we list properly the maintained software (nEXT browser) and still reference others, but below (Closure, Lispkit), with less details. Is that ok for you ?

This could fix https://github.com/CodyReichert/awesome-cl/pull/127.

Regards

### CODE REVIEW

**Comment by azzamsa** [comment]
oh, by any chance.
I also thought about this yesterday, with some candidates

- sorting from the most active maintained project, but it will be difficult over time if there is a new project  where we have to check it and sort it one by one again.
- keep sorting alphabetically, but give a certain icon in front of the list name ([like this](https://github.com/azzamsa/awesome-lisp-companies/blob/master/README.md) for the project editor of choice or recommended project

**Comment by vindarel** [comment]
Cool :)

But what do you think of this PR, do you accept or reject this candidate solution ? If you want we keep a list under a "see also" or "Unmaintained" line, like this:

### A subsection

- a current software

See also / old / unmaintained:

- another old
- unmaintained

> sorting from the most active maintained project, 

that would still not be clear enough to me.

> but it will be difficult over time if there is a new project where we have to check it and sort it one by one again.

fair work for this awesome list IMO :)

> an icon

why not. Can be added when there are more than one nice current software.

---

> oh, by any chance

I *think* that's a negation

**Comment by azzamsa** [comment]
> I think that's a negation

Sorry English is not my first tongue, I am sorry for misinterpretation.

> unmaintained

we have to remember that CL does not evolve like any other language, so as long we still in HyperSpec all those *unmaintained* things are still usable and run well.

**Comment by azzamsa** [comment]
If the parameter is limited only to active commit, JSCL is more active than parenscript, but parenscript have more feature than jscl.

I think I will choose my second option, to give an icon so that non-lipser know what best app in certain section.

**Comment by vindarel** [comment]
> we have to remember that CL does not evolve like any other language, so as long we still in HyperSpec [?] all those unmaintained things are still usable and run well.

I agree for a librarie, but I have to contradict you for software. And in our case, Lispkit is unfinished and unusable (did you try it ?) and Closure is based on McClim (ridiculous UI to today standards) and wasn't updated in 11 years, which is enormous for the web.

Besides it says:

> supports HTML-4 and CSS-1 plus the essential bits of CSS-2; 

I expect its use to be disastrous today, but I didn't try. Anyway, we can hardly recommend it and put it at the same level of nEXT.

> If the parameter is limited only to active commit, JSCL is more active than parenscript, but parenscript have more feature than jscl.

We would list the two here, no pb. But the difference is huge for those browsers.

> Sorry English is not my first tongue, I am sorry for misinterpretation.

No pb ! We'll learn. (it isn't my first /language/ either (tongue is the muscle).

**Comment by azzamsa** [comment]
>I agree for a librarie, but I have to contradict you for software. And in our case, Lispkit is unfinished and unusable (did you try it ?) and Closure is based on McClim (ridiculous UI to today standards) and wasn't updated in 11 years, which is enormous for the web.

This is the key. I thought lispkit and closure is well.

Alright then. let's try to put **see also**

**Comment by azzamsa** [comment]
@vindarel  If you tried on the the app in list, and it is unmaintained for very very long years, and not suit to show for CL environment today, don't hesitate to move to *see also*

**Comment by azzamsa** [comment]
in [text editor section](https://github.com/azzamsa/awesome-cl-software#editors) Lem is the one that has active development while others is not.

I think I have to sort the list not by alphabetical order, instead I will use the most actively maintained or the most popular. as what awesome-emacs does [awesome-emacs order of items](https://github.com/emacs-tw/awesome-emacs#the-order-of-items

**Comment by vindarel** [comment]
Ok I'll keep an eye on the list, and this order makes sense indeed (as long as you explain too). Thanks.

**Pull request merged**
