### PR TITLE
add Turtl, note taking app

### PR DESCRIPTION
**Pull request by vindarel**

### CODE REVIEW

**Comment by azzamsa** [comment]
Hi Vindarel.

Thanks for contributing, but I think you don't pull your repo to this repo HEAD, we have a conflict.

**Comment by azzamsa** [comment]
Please do not add any other thing except

- `[link] - [description] - [license]`

**Comment by vindarel** [comment]
saw that ;) too bad for not allowing further information IMO, but as you wish.

**Comment by azzamsa** [comment]
Further information is great, but if we add further information to each list, this list will not clean and tidy.  people who need something will always search deeper by themselves. :)

Can we put Turtl to `#Productivity` section, instead of make another section ?

**Comment by vindarel** [comment]
ok thats' better. I rebased.

it would be a bit larger, but I like some context. Anyway, no big deal.

**Comment by azzamsa** [comment]
Thank you for your contribution, Vindarel.

**Pull request merged**
